version: '3'
services: 
  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  backend:
    build: 
      dockerfile: Dockerfile.dev
      context: ./backend
    volumes:
      # everything below the server directory goes to app 
      - ./backend:/app
  frontend:
    build: 
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes: 
      - /app/node_modules
      - ./frontend:/app
      