apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      component: frontend
  template:
    metadata: 
      labels:
        component: frontend
    spec: 
      containers: 
        - name: client
          image: ssy01013/guess-frontend
          ports:
            - containerPort: 3000

